/**
 * Firebase Configuration
 * Initialize Firebase and Firestore
 */

// Firebase configuration - Replace with your actual credentials
const firebaseConfig = {
    apiKey: "AIzaSyBpOKVdsOWJtiN2MgYxQIkUctW8nfU-7w8",
    authDomain: "chronotrack-c5c02.firebaseapp.com",
    projectId: "chronotrack-c5c02",
    storageBucket: "chronotrack-c5c02.firebasestorage.app",
    messagingSenderId: "166910042878",
    appId: "1:166910042878:web:49985f2ee0417186d1bbaf",
    measurementId: "G-JL2HC74BC2"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Initialize Realtime Database
const database = firebase.database();

// Initialize Authentication
const auth = firebase.auth();

// Realtime Database References
const usersRef = database.ref('users');
const eventsRef = database.ref('events');
const tasksRef = database.ref('tasks');
const goalsRef = database.ref('goals');
const habitsRef = database.ref('habits');
const notesRef = database.ref('notes');
const expensesRef = database.ref('expenses');
const timeLogsRef = database.ref('timeLogs');

// Firestore Rules (to be deployed separately)
/*
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    // Deny all access by default
    match /{document=**} {
      allow read, write: if false;
    }
    
    // Users collection - each user can only access their own data
    match /users/{userId} {
      allow read, write: if request.auth.uid == userId;
      
      // Subcollections
      match /profile/{document=**} {
        allow read, write: if request.auth.uid == userId;
      }
      
      match /preferences/{document=**} {
        allow read, write: if request.auth.uid == userId;
      }
      
      match /notifications/{document=**} {
        allow read, write: if request.auth.uid == userId;
      }
    }
    
    // Events collection
    match /events/{eventId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Tasks collection
    match /tasks/{taskId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Goals collection
    match /goals/{goalId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Habits collection
    match /habits/{habitId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Notes collection
    match /notes/{noteId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Expenses collection
    match /expenses/{expenseId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
    
    // Time Logs collection
    match /timeLogs/{logId} {
      allow read, write: if request.auth.uid == resource.data.userId;
      allow create: if request.auth.uid == request.resource.data.userId;
    }
  }
}
*/

/**
 * User Data Structure
 */
const userDataTemplate = {
    userId: "", // Set by Firebase Auth
    displayName: "",
    email: "",
    profilePicture: "",
    timezone: "UTC",
    locale: "en-US",
    theme: "light", // light or dark
    accentColor: "violet", // violet, blue, green, red
    createdAt: new Date(),
    lastLogin: new Date(),
    preferences: {
        emailNotifications: true,
        pushNotifications: true,
        analyticsEnabled: true,
        defaultCalendarView: "monthly", // daily, weekly, monthly
        defaultTaskView: "list", // list or board
        weekStartDay: 0 // 0 = Sunday, 1 = Monday
    }
};

/**
 * Event Data Structure
 */
const eventTemplate = {
    eventId: "", // Generated by Firestore
    userId: "", // Set from current user
    title: "",
    description: "",
    category: "work", // work, personal, health, finance, learning, social
    startTime: new Date(),
    endTime: new Date(),
    isAllDay: false,
    isRecurring: false,
    recurringPattern: null, // daily, weekly, monthly, custom
    reminders: [300000], // in milliseconds before event
    color: "#6366f1",
    location: "",
    attendees: [],
    createdAt: new Date(),
    updatedAt: new Date()
};

/**
 * Task Data Structure
 */
const taskTemplate = {
    taskId: "", // Generated by Firestore
    userId: "", // Set from current user
    title: "",
    description: "",
    notes: "",
    status: "pending", // pending, in-progress, completed, overdue, on-hold
    priority: "medium", // low, medium, high
    dueDate: new Date(),
    dueTime: "",
    category: "work",
    subtasks: [
        {
            id: "",
            title: "",
            completed: false
        }
    ],
    projectId: "",
    tags: [],
    attachments: [],
    estimatedHours: 0,
    actualHours: 0,
    percentComplete: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    completedAt: null
};

/**
 * Goal Data Structure
 */
const goalTemplate = {
    goalId: "", // Generated by Firestore
    userId: "", // Set from current user
    title: "",
    description: "",
    category: "personal",
    type: "short-term", // short-term or long-term
    targetDate: new Date(),
    priority: "medium",
    status: "active", // active, completed, abandoned
    milestones: [
        {
            id: "",
            title: "",
            targetDate: new Date(),
            completed: false,
            completedAt: null
        }
    ],
    progress: 0, // percentage
    tags: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    completedAt: null
};

/**
 * Habit Data Structure
 */
const habitTemplate = {
    habitId: "", // Generated by Firestore
    userId: "", // Set from current user
    title: "",
    description: "",
    category: "personal",
    frequency: "daily", // daily, weekly, custom
    daysOfWeek: [1, 2, 3, 4, 5], // 0-6, 0 = Sunday
    customDays: [],
    startDate: new Date(),
    targetStreak: 0,
    currentStreak: 0,
    longestStreak: 0,
    completions: {
        // Date -> boolean
    },
    missedDays: 0,
    successRate: 0,
    tags: [],
    createdAt: new Date(),
    updatedAt: new Date()
};

/**
 * Note Data Structure
 */
const noteTemplate = {
    noteId: "", // Generated by Firestore
    userId: "", // Set from current user
    title: "",
    content: "",
    type: "note", // note, journal, checklist
    tags: [],
    linkedTo: {
        eventId: null,
        taskId: null,
        goalId: null
    },
    isPinned: false,
    color: "#ffffff",
    createdAt: new Date(),
    updatedAt: new Date()
};

/**
 * Expense Data Structure
 */
const expenseTemplate = {
    expenseId: "", // Generated by Firestore
    userId: "", // Set from current user
    description: "",
    amount: 0,
    currency: "USD",
    category: "other", // food, transport, entertainment, health, utilities, etc
    date: new Date(),
    paymentMethod: "cash", // cash, card, online, other
    tags: [],
    notes: "",
    receipt: null,
    createdAt: new Date(),
    updatedAt: new Date()
};

/**
 * Time Log Data Structure
 */
const timeLogTemplate = {
    logId: "", // Generated by Firestore
    userId: "", // Set from current user
    activity: "",
    category: "work",
    duration: 0, // in minutes
    startTime: new Date(),
    endTime: new Date(),
    notes: "",
    tags: [],
    billable: false,
    createdAt: new Date(),
    updatedAt: new Date()
};

/**
 * Analytics Computed Data Structure
 */
const analyticsTemplate = {
    userId: "",
    period: "monthly", // daily, weekly, monthly, yearly
    taskCompletionRate: 0,
    habitConsistency: 0,
    timeByCategory: {},
    expensesByCategory: {},
    goalProgress: {},
    productivityScore: 0,
    computedAt: new Date()
};

/**
 * Helper function to set user ID in templates
 */
function setUserIdInTemplate(template, userId) {
    const copy = JSON.parse(JSON.stringify(template));
    copy.userId = userId;
    return copy;
}

/**
 * Export functions for use in other modules
 */
window.FirebaseConfig = {
    database,
    auth,
    usersRef,
    eventsRef,
    tasksRef,
    goalsRef,
    habitsRef,
    notesRef,
    expensesRef,
    timeLogsRef,
    userDataTemplate,
    eventTemplate,
    taskTemplate,
    goalTemplate,
    habitTemplate,
    noteTemplate,
    expenseTemplate,
    timeLogTemplate,
    analyticsTemplate,
    setUserIdInTemplate
};
